// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ValueInsight.Backend.Data;

#nullable disable

namespace ValueInsight.Backend.Migrations
{
    [DbContext(typeof(ValueInsightDbContext))]
    [Migration("20260305074523_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ValueInsight.Backend.Models.CulturalFitResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AlignmentScore")
                        .HasColumnType("float");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("CulturalFitResults");
                });

            modelBuilder.Entity("ValueInsight.Backend.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("ValueInsight.Backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ValueInsight.Backend.Models.UserValue", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("ValueId")
                        .HasColumnType("int");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.HasKey("UserId", "ValueId");

                    b.HasIndex("ValueId");

                    b.ToTable("UserValues");
                });

            modelBuilder.Entity("ValueInsight.Backend.Models.Value", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BehaviorIndicator")
                        .HasMaxLength(240)
                        .HasColumnType("nvarchar(240)");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("ShortDefinition")
                        .HasMaxLength(240)
                        .HasColumnType("nvarchar(240)");

                    b.HasKey("Id");

                    b.ToTable("Values");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 1,
                            Name = "Trust"
                        },
                        new
                        {
                            Id = 2,
                            Category = 1,
                            Name = "Respect"
                        },
                        new
                        {
                            Id = 3,
                            Category = 1,
                            Name = "Transparency"
                        },
                        new
                        {
                            Id = 4,
                            Category = 2,
                            Name = "Results"
                        },
                        new
                        {
                            Id = 5,
                            Category = 2,
                            Name = "Efficiency"
                        },
                        new
                        {
                            Id = 6,
                            Category = 3,
                            Name = "Structure"
                        },
                        new
                        {
                            Id = 7,
                            Category = 4,
                            Name = "Freedom"
                        },
                        new
                        {
                            Id = 8,
                            Category = 5,
                            Name = "Innovation"
                        },
                        new
                        {
                            Id = 9,
                            Category = 6,
                            Name = "Purpose"
                        });
                });

            modelBuilder.Entity("ValueInsight.Backend.Models.CulturalFitResult", b =>
                {
                    b.HasOne("ValueInsight.Backend.Models.Team", "Team")
                        .WithMany("CulturalFitResults")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("ValueInsight.Backend.Models.User", b =>
                {
                    b.HasOne("ValueInsight.Backend.Models.Team", "Team")
                        .WithMany("Users")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("ValueInsight.Backend.Models.UserValue", b =>
                {
                    b.HasOne("ValueInsight.Backend.Models.User", "User")
                        .WithMany("UserValues")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ValueInsight.Backend.Models.Value", "Value")
                        .WithMany("UserValues")
                        .HasForeignKey("ValueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Value");
                });

            modelBuilder.Entity("ValueInsight.Backend.Models.Team", b =>
                {
                    b.Navigation("CulturalFitResults");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("ValueInsight.Backend.Models.User", b =>
                {
                    b.Navigation("UserValues");
                });

            modelBuilder.Entity("ValueInsight.Backend.Models.Value", b =>
                {
                    b.Navigation("UserValues");
                });
#pragma warning restore 612, 618
        }
    }
}
