// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ValueInsight.Backend.Data;

#nullable disable

namespace ValueInsight.Backend.Migrations
{
    [DbContext(typeof(ValueInsightDbContext))]
    [Migration("20260318175540_MakeTeamOptional")]
    partial class MakeTeamOptional
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ValueInsight.Backend.Models.CulturalFitResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AlignmentScore")
                        .HasColumnType("float");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("CulturalFitResults");
                });

            modelBuilder.Entity("ValueInsight.Backend.Models.ReflectionAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("QuestionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponseText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ReflectionAnswers");
                });

            modelBuilder.Entity("ValueInsight.Backend.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Engineering"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Product"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Design"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Marketing"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Operations"
                        });
                });

            modelBuilder.Entity("ValueInsight.Backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ValueInsight.Backend.Models.UserValue", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("ValueId")
                        .HasColumnType("int");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.HasKey("UserId", "ValueId");

                    b.HasIndex("ValueId");

                    b.ToTable("UserValues");
                });

            modelBuilder.Entity("ValueInsight.Backend.Models.Value", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BehaviorIndicator")
                        .HasMaxLength(240)
                        .HasColumnType("nvarchar(240)");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("ShortDefinition")
                        .HasMaxLength(240)
                        .HasColumnType("nvarchar(240)");

                    b.HasKey("Id");

                    b.ToTable("Values");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BehaviorIndicator = "Delegates and gives others room.",
                            Category = 1,
                            Name = "Trust",
                            ShortDefinition = "I assume others have good intentions."
                        },
                        new
                        {
                            Id = 2,
                            BehaviorIndicator = "Speaks respectfully even in disagreement.",
                            Category = 1,
                            Name = "Respect",
                            ShortDefinition = "I treat others with dignity."
                        },
                        new
                        {
                            Id = 3,
                            BehaviorIndicator = "Listens before reacting.",
                            Category = 1,
                            Name = "Empathy",
                            ShortDefinition = "I try to understand other perspectives."
                        },
                        new
                        {
                            Id = 4,
                            BehaviorIndicator = "Checks in on others regularly.",
                            Category = 1,
                            Name = "Care",
                            ShortDefinition = "I care about people’s wellbeing."
                        },
                        new
                        {
                            Id = 5,
                            BehaviorIndicator = "Invites others into decisions.",
                            Category = 1,
                            Name = "Collaboration",
                            ShortDefinition = "Shared success matters to me."
                        },
                        new
                        {
                            Id = 6,
                            BehaviorIndicator = "Communicates candidly.",
                            Category = 1,
                            Name = "Openness",
                            ShortDefinition = "I share thoughts and feelings honestly."
                        },
                        new
                        {
                            Id = 7,
                            BehaviorIndicator = "Explains reasons behind decisions.",
                            Category = 1,
                            Name = "Transparency",
                            ShortDefinition = "I am clear about intentions."
                        },
                        new
                        {
                            Id = 8,
                            BehaviorIndicator = "Supports the group in tough situations.",
                            Category = 1,
                            Name = "Loyalty",
                            ShortDefinition = "I stand by my team."
                        },
                        new
                        {
                            Id = 9,
                            BehaviorIndicator = "Makes space for quieter voices.",
                            Category = 1,
                            Name = "Inclusion",
                            ShortDefinition = "Everyone should feel welcome."
                        },
                        new
                        {
                            Id = 10,
                            BehaviorIndicator = "Applies standards consistently.",
                            Category = 1,
                            Name = "Fairness",
                            ShortDefinition = "Decisions should be impartial."
                        },
                        new
                        {
                            Id = 11,
                            BehaviorIndicator = "Keeps attention on outcomes.",
                            Category = 2,
                            Name = "Results Focus",
                            ShortDefinition = "I prioritize delivery."
                        },
                        new
                        {
                            Id = 12,
                            BehaviorIndicator = "Removes unnecessary steps.",
                            Category = 2,
                            Name = "Efficiency",
                            ShortDefinition = "Resources should be used wisely."
                        },
                        new
                        {
                            Id = 13,
                            BehaviorIndicator = "Reviews details carefully.",
                            Category = 2,
                            Name = "Quality",
                            ShortDefinition = "Work should meet a high standard."
                        },
                        new
                        {
                            Id = 14,
                            BehaviorIndicator = "Follows through without reminders.",
                            Category = 2,
                            Name = "Responsibility",
                            ShortDefinition = "I own my commitments."
                        },
                        new
                        {
                            Id = 15,
                            BehaviorIndicator = "Sets and pursues stretch goals.",
                            Category = 2,
                            Name = "Achievement Drive",
                            ShortDefinition = "I want to reach ambitious goals."
                        },
                        new
                        {
                            Id = 16,
                            BehaviorIndicator = "Makes timely decisions.",
                            Category = 2,
                            Name = "Decisiveness",
                            ShortDefinition = "I prefer action over hesitation."
                        },
                        new
                        {
                            Id = 17,
                            BehaviorIndicator = "Defines ownership and outcomes.",
                            Category = 2,
                            Name = "Clarity",
                            ShortDefinition = "Expectations should be clear."
                        },
                        new
                        {
                            Id = 18,
                            BehaviorIndicator = "Keeps routines and commitments.",
                            Category = 2,
                            Name = "Discipline",
                            ShortDefinition = "I do what is required."
                        },
                        new
                        {
                            Id = 19,
                            BehaviorIndicator = "Benchmarks against strong peers.",
                            Category = 2,
                            Name = "Competitiveness",
                            ShortDefinition = "We should strive to be the best."
                        },
                        new
                        {
                            Id = 20,
                            BehaviorIndicator = "Delivers consistently.",
                            Category = 2,
                            Name = "Reliability",
                            ShortDefinition = "I keep my promises."
                        },
                        new
                        {
                            Id = 21,
                            BehaviorIndicator = "Creates process and order.",
                            Category = 3,
                            Name = "Structure",
                            ShortDefinition = "Clear frameworks are important."
                        },
                        new
                        {
                            Id = 22,
                            BehaviorIndicator = "Plans before acting.",
                            Category = 3,
                            Name = "Planning",
                            ShortDefinition = "Preparation matters."
                        },
                        new
                        {
                            Id = 23,
                            BehaviorIndicator = "Prefers clear expectations.",
                            Category = 3,
                            Name = "Predictability",
                            ShortDefinition = "Stability creates safety."
                        },
                        new
                        {
                            Id = 24,
                            BehaviorIndicator = "Flags risks early.",
                            Category = 3,
                            Name = "Safety",
                            ShortDefinition = "Risks should be minimized."
                        },
                        new
                        {
                            Id = 25,
                            BehaviorIndicator = "Applies processes the same way.",
                            Category = 3,
                            Name = "Consistency",
                            ShortDefinition = "Rules should be followed."
                        },
                        new
                        {
                            Id = 26,
                            BehaviorIndicator = "Keeps work organized.",
                            Category = 3,
                            Name = "Order",
                            ShortDefinition = "System beats chaos."
                        },
                        new
                        {
                            Id = 27,
                            BehaviorIndicator = "Considers future implications.",
                            Category = 3,
                            Name = "Long-Term Thinking",
                            ShortDefinition = "Think several steps ahead."
                        },
                        new
                        {
                            Id = 28,
                            BehaviorIndicator = "Protects continuity.",
                            Category = 3,
                            Name = "Stability",
                            ShortDefinition = "Avoid unnecessary change."
                        },
                        new
                        {
                            Id = 29,
                            BehaviorIndicator = "Tracks progress closely.",
                            Category = 3,
                            Name = "Control",
                            ShortDefinition = "I want oversight."
                        },
                        new
                        {
                            Id = 30,
                            BehaviorIndicator = "Defines responsibilities explicitly.",
                            Category = 3,
                            Name = "Role Clarity",
                            ShortDefinition = "Roles should be clear."
                        },
                        new
                        {
                            Id = 31,
                            BehaviorIndicator = "Prefers autonomy in execution.",
                            Category = 4,
                            Name = "Freedom",
                            ShortDefinition = "I want room to act."
                        },
                        new
                        {
                            Id = 32,
                            BehaviorIndicator = "Works well with limited supervision.",
                            Category = 4,
                            Name = "Independence",
                            ShortDefinition = "I make my own decisions."
                        },
                        new
                        {
                            Id = 33,
                            BehaviorIndicator = "Adjusts approach quickly.",
                            Category = 4,
                            Name = "Flexibility",
                            ShortDefinition = "Adaptability matters."
                        },
                        new
                        {
                            Id = 34,
                            BehaviorIndicator = "Acts despite uncertainty.",
                            Category = 4,
                            Name = "Courage",
                            ShortDefinition = "I dare to take risks."
                        },
                        new
                        {
                            Id = 35,
                            BehaviorIndicator = "Speaks up when something feels wrong.",
                            Category = 4,
                            Name = "Integrity",
                            ShortDefinition = "I stand by my principles."
                        },
                        new
                        {
                            Id = 36,
                            BehaviorIndicator = "Expresses individual style and views.",
                            Category = 4,
                            Name = "Self-Expression",
                            ShortDefinition = "I can be myself."
                        },
                        new
                        {
                            Id = 37,
                            BehaviorIndicator = "Solves problems independently.",
                            Category = 4,
                            Name = "Self-Reliance",
                            ShortDefinition = "I prefer minimal dependence on others."
                        },
                        new
                        {
                            Id = 38,
                            BehaviorIndicator = "Starts things proactively.",
                            Category = 4,
                            Name = "Initiative",
                            ShortDefinition = "I act without being told."
                        },
                        new
                        {
                            Id = 39,
                            BehaviorIndicator = "Acts in line with own beliefs.",
                            Category = 4,
                            Name = "Authenticity",
                            ShortDefinition = "I want to be genuine."
                        },
                        new
                        {
                            Id = 40,
                            BehaviorIndicator = "Takes ownership of action.",
                            Category = 4,
                            Name = "Agency",
                            ShortDefinition = "I want power to move things forward."
                        },
                        new
                        {
                            Id = 41,
                            BehaviorIndicator = "Seeks feedback and new knowledge.",
                            Category = 5,
                            Name = "Learning",
                            ShortDefinition = "I want to keep developing."
                        },
                        new
                        {
                            Id = 42,
                            BehaviorIndicator = "Suggests new approaches.",
                            Category = 5,
                            Name = "Innovation",
                            ShortDefinition = "New ideas matter."
                        },
                        new
                        {
                            Id = 43,
                            BehaviorIndicator = "Generates original ideas.",
                            Category = 5,
                            Name = "Creativity",
                            ShortDefinition = "I like thinking differently."
                        },
                        new
                        {
                            Id = 44,
                            BehaviorIndicator = "Adapts quickly to new conditions.",
                            Category = 5,
                            Name = "Change Readiness",
                            ShortDefinition = "I embrace change."
                        },
                        new
                        {
                            Id = 45,
                            BehaviorIndicator = "Investigates before concluding.",
                            Category = 5,
                            Name = "Curiosity",
                            ShortDefinition = "I explore and ask questions."
                        },
                        new
                        {
                            Id = 46,
                            BehaviorIndicator = "Looks for continuous improvement.",
                            Category = 5,
                            Name = "Improvement",
                            ShortDefinition = "Small steps forward matter."
                        },
                        new
                        {
                            Id = 47,
                            BehaviorIndicator = "Connects today’s work to the future.",
                            Category = 5,
                            Name = "Vision",
                            ShortDefinition = "I think long-term and forward."
                        },
                        new
                        {
                            Id = 48,
                            BehaviorIndicator = "Looks for opportunities to scale.",
                            Category = 5,
                            Name = "Growth",
                            ShortDefinition = "Expansion and development are positive."
                        },
                        new
                        {
                            Id = 49,
                            BehaviorIndicator = "Runs small trials before scaling.",
                            Category = 5,
                            Name = "Experimentation",
                            ShortDefinition = "Test and adjust."
                        },
                        new
                        {
                            Id = 50,
                            BehaviorIndicator = "Takes on demanding goals.",
                            Category = 5,
                            Name = "Challenge",
                            ShortDefinition = "I seek stretch."
                        },
                        new
                        {
                            Id = 51,
                            BehaviorIndicator = "Connects work to a larger why.",
                            Category = 6,
                            Name = "Purpose",
                            ShortDefinition = "Work should feel meaningful."
                        },
                        new
                        {
                            Id = 52,
                            BehaviorIndicator = "Considers societal impact.",
                            Category = 6,
                            Name = "Social Responsibility",
                            ShortDefinition = "We should contribute to something bigger."
                        },
                        new
                        {
                            Id = 53,
                            BehaviorIndicator = "Balances present and future needs.",
                            Category = 6,
                            Name = "Sustainability",
                            ShortDefinition = "Long-term impact matters."
                        },
                        new
                        {
                            Id = 54,
                            BehaviorIndicator = "Raises ethical concerns openly.",
                            Category = 6,
                            Name = "Ethics",
                            ShortDefinition = "Decisions should be morally sound."
                        },
                        new
                        {
                            Id = 55,
                            BehaviorIndicator = "Removes obstacles for others.",
                            Category = 6,
                            Name = "Servant Leadership",
                            ShortDefinition = "I support others to succeed."
                        },
                        new
                        {
                            Id = 56,
                            BehaviorIndicator = "Seeks meaningful outcomes.",
                            Category = 6,
                            Name = "Impact",
                            ShortDefinition = "I want to make a difference."
                        },
                        new
                        {
                            Id = 57,
                            BehaviorIndicator = "Brings visible energy to work.",
                            Category = 6,
                            Name = "Passion",
                            ShortDefinition = "I am driven by engagement."
                        },
                        new
                        {
                            Id = 58,
                            BehaviorIndicator = "Shows dedication over time.",
                            Category = 6,
                            Name = "Commitment",
                            ShortDefinition = "I invest my energy fully."
                        },
                        new
                        {
                            Id = 59,
                            BehaviorIndicator = "Makes choices anchored in principles.",
                            Category = 6,
                            Name = "Values-Based Action",
                            ShortDefinition = "I act in line with my values."
                        },
                        new
                        {
                            Id = 60,
                            BehaviorIndicator = "Protects healthy boundaries.",
                            Category = 6,
                            Name = "Balance",
                            ShortDefinition = "Work and life should be sustainable."
                        });
                });

            modelBuilder.Entity("ValueInsight.Backend.Models.CulturalFitResult", b =>
                {
                    b.HasOne("ValueInsight.Backend.Models.Team", "Team")
                        .WithMany("CulturalFitResults")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("ValueInsight.Backend.Models.ReflectionAnswer", b =>
                {
                    b.HasOne("ValueInsight.Backend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ValueInsight.Backend.Models.User", b =>
                {
                    b.HasOne("ValueInsight.Backend.Models.Team", "Team")
                        .WithMany("Users")
                        .HasForeignKey("TeamId");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("ValueInsight.Backend.Models.UserValue", b =>
                {
                    b.HasOne("ValueInsight.Backend.Models.User", "User")
                        .WithMany("UserValues")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ValueInsight.Backend.Models.Value", "Value")
                        .WithMany("UserValues")
                        .HasForeignKey("ValueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Value");
                });

            modelBuilder.Entity("ValueInsight.Backend.Models.Team", b =>
                {
                    b.Navigation("CulturalFitResults");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("ValueInsight.Backend.Models.User", b =>
                {
                    b.Navigation("UserValues");
                });

            modelBuilder.Entity("ValueInsight.Backend.Models.Value", b =>
                {
                    b.Navigation("UserValues");
                });
#pragma warning restore 612, 618
        }
    }
}
