// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ValueInsight.Backend.Data;

#nullable disable

namespace ValueInsight.Backend.Migrations
{
    [DbContext(typeof(ValueInsightDbContext))]
    [Migration("20260327185300_newmodels")]
    partial class newmodels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ValueInsight.Backend.Models.AssessmentReflectionAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssessmentRunId")
                        .HasColumnType("int");

                    b.Property<string>("QuestionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponseText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentRunId");

                    b.ToTable("AssessmentReflectionAnswers");
                });

            modelBuilder.Entity("ValueInsight.Backend.Models.AssessmentRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AssessmentRuns");
                });

            modelBuilder.Entity("ValueInsight.Backend.Models.AssessmentValueSelection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssessmentRunId")
                        .HasColumnType("int");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<int>("ValueId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentRunId");

                    b.HasIndex("ValueId");

                    b.ToTable("AssessmentValueSelections");
                });

            modelBuilder.Entity("ValueInsight.Backend.Models.CulturalFitResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AlignmentScore")
                        .HasColumnType("float");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("CulturalFitResults");
                });

            modelBuilder.Entity("ValueInsight.Backend.Models.ReflectionAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("QuestionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponseText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ReflectionAnswers");
                });

            modelBuilder.Entity("ValueInsight.Backend.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("ValueInsight.Backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ValueInsight.Backend.Models.UserValue", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("ValueId")
                        .HasColumnType("int");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.HasKey("UserId", "ValueId");

                    b.HasIndex("ValueId");

                    b.ToTable("UserValues");
                });

            modelBuilder.Entity("ValueInsight.Backend.Models.Value", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BehaviorIndicator")
                        .HasMaxLength(240)
                        .HasColumnType("nvarchar(240)");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("ShortDefinition")
                        .HasMaxLength(240)
                        .HasColumnType("nvarchar(240)");

                    b.HasKey("Id");

                    b.ToTable("Values");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 1,
                            Name = "Trust"
                        },
                        new
                        {
                            Id = 2,
                            Category = 1,
                            Name = "Respect"
                        },
                        new
                        {
                            Id = 3,
                            Category = 1,
                            Name = "Transparency"
                        },
                        new
                        {
                            Id = 4,
                            Category = 2,
                            Name = "Results"
                        },
                        new
                        {
                            Id = 5,
                            Category = 2,
                            Name = "Efficiency"
                        },
                        new
                        {
                            Id = 6,
                            Category = 3,
                            Name = "Structure"
                        },
                        new
                        {
                            Id = 7,
                            Category = 4,
                            Name = "Freedom"
                        },
                        new
                        {
                            Id = 8,
                            Category = 5,
                            Name = "Innovation"
                        },
                        new
                        {
                            Id = 9,
                            Category = 6,
                            Name = "Purpose"
                        });
                });

            modelBuilder.Entity("ValueInsight.Backend.Models.AssessmentReflectionAnswer", b =>
                {
                    b.HasOne("ValueInsight.Backend.Models.AssessmentRun", "AssessmentRun")
                        .WithMany("ReflectionAnswers")
                        .HasForeignKey("AssessmentRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssessmentRun");
                });

            modelBuilder.Entity("ValueInsight.Backend.Models.AssessmentRun", b =>
                {
                    b.HasOne("ValueInsight.Backend.Models.User", "User")
                        .WithMany("AssessmentRuns")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ValueInsight.Backend.Models.AssessmentValueSelection", b =>
                {
                    b.HasOne("ValueInsight.Backend.Models.AssessmentRun", "AssessmentRun")
                        .WithMany("ValueSelections")
                        .HasForeignKey("AssessmentRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ValueInsight.Backend.Models.Value", "Value")
                        .WithMany()
                        .HasForeignKey("ValueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssessmentRun");

                    b.Navigation("Value");
                });

            modelBuilder.Entity("ValueInsight.Backend.Models.CulturalFitResult", b =>
                {
                    b.HasOne("ValueInsight.Backend.Models.Team", "Team")
                        .WithMany("CulturalFitResults")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("ValueInsight.Backend.Models.ReflectionAnswer", b =>
                {
                    b.HasOne("ValueInsight.Backend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ValueInsight.Backend.Models.User", b =>
                {
                    b.HasOne("ValueInsight.Backend.Models.Team", "Team")
                        .WithMany("Users")
                        .HasForeignKey("TeamId");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("ValueInsight.Backend.Models.UserValue", b =>
                {
                    b.HasOne("ValueInsight.Backend.Models.User", "User")
                        .WithMany("UserValues")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ValueInsight.Backend.Models.Value", "Value")
                        .WithMany("UserValues")
                        .HasForeignKey("ValueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Value");
                });

            modelBuilder.Entity("ValueInsight.Backend.Models.AssessmentRun", b =>
                {
                    b.Navigation("ReflectionAnswers");

                    b.Navigation("ValueSelections");
                });

            modelBuilder.Entity("ValueInsight.Backend.Models.Team", b =>
                {
                    b.Navigation("CulturalFitResults");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("ValueInsight.Backend.Models.User", b =>
                {
                    b.Navigation("AssessmentRuns");

                    b.Navigation("UserValues");
                });

            modelBuilder.Entity("ValueInsight.Backend.Models.Value", b =>
                {
                    b.Navigation("UserValues");
                });
#pragma warning restore 612, 618
        }
    }
}
